# Generated by Django 5.1.4 on 2024-12-07 15:12

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('profileimage', models.ImageField(default='uploads/profiles/<django.db.models.fields.CharField>.jpeg', upload_to='uploads/profiles')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('notificationSFX', models.BooleanField(default=True)),
            ],
        ),
    ]
